<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'administrator',
                'email' => 'admin@dost.com',
                'email_verified_at' => '2022-12-20 21:06:09',
                'password' => '$2y$10$A4olEZE1blc48hDnZohukugUMjjtXQMJX2fvlAOHPgwpQG6AdgKEC',
                'avatar' => 'avatar.jpg',
                'role' => 'Super Administrator',
                'is_active' => 1,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:09',
                'updated_at' => '2022-12-20 21:06:09',
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'RBA-1223',
                'email' => 'rdba2004@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ywslHLzPeWl1xaLGhAX/Wu3rVbGOgHji2eQFTiY6R6X.Q5mf5x5GK',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'ITA-0107',
                'email' => 'red_belle22@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$gW26N7TMqMTiaqjJKRqHguNEzgzVUDzPATMgp7BpG9k2ySgS8QTbi',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'GCA-1029',
                'email' => 'giancarloacejas@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Uj7qKFr4.L6OWtKoYbojN.b.sFqhQfOtKvkYfxFDTre3WaeBcl.pe',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'HTA-0316',
                'email' => 'HERMAYJOYCEA@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$IzXBsP8v5acCzOgfkYyAWuNMrZO4lo.alNm6QHNyE.ng3H8J1q9tK',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'SVA - 0308',
                'email' => 'stenelrizza@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$guTBIu68J9ConC4hZEsb1eXddr4D8vqsH5zlkI54iNDMfWADu4TX6',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            6 => 
            array (
                'id' => 7,
                'username' => 'MDA-0206',
                'email' => 'merly02.md@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$pD6z9YmdCIjrguCcFHPSteo9dGiPU2BbnBRVjBWNhhPog1BVlLcwa',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            7 => 
            array (
                'id' => 8,
                'username' => 'NMA-0601',
                'email' => 'nuhman.aljani@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$8SWXkvTmq45/fLavppVP9uDRbK3KxZ9j9wTMyDu/GrY3yxz.creuG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            8 => 
            array (
                'id' => 9,
                'username' => 'JEA-1124',
                'email' => 'alvarez.judilyn24@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$sMBWpo/lNtbLtcuOauTtRuKvsU0QrFqqvfA7hZINuj7SQGybfFUzy',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            9 => 
            array (
                'id' => 10,
                'username' => 'WPA-0718',
                'email' => 'wpa-0718@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ep3iAZY4l/s5XCYhKWnX.eulcmHSkVTVY/rMSuuPWRwBDWJn88I0e',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            10 => 
            array (
                'id' => 11,
                'username' => 'JAA-0615',
                'email' => 'jovitaapduhan@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$L5hb0s1ggy5N2rQ4qSlAcuk1yrxKk96SuBEVXobUGdJMV1.aKKMRK',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            11 => 
            array (
                'id' => 12,
                'username' => 'SBA-0801',
                'email' => 'andossheila@gmail.com
drrm.dost9@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$T.kTpdZJ5tIkSRfI.E1Q.uX6A5WyC3P5Fci97s4Kfy1j.2BUEMwp2',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            12 => 
            array (
                'id' => 13,
                'username' => 'ZFA-0312',
                'email' => 'zorenantonio@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$d9BezRcL1yDFQEWlnv.DbeEu0BNXDTBUyU1V.3UJ0x8I1mTfetXbu',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            13 => 
            array (
                'id' => 14,
                'username' => 'JPA-1101',
                'email' => 'jeyzel_aparri@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZcqwD2hl.ISECpSGq14MkOEdwjijEOG2xu/2Ad683Y7U3cF74jgU6',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            14 => 
            array (
                'id' => 15,
                'username' => 'RJA-0624',
                'email' => 'zamboconsortium@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0woqQpavkwQX1xz0cm6QNuv7/YBEdW9w6J1pSVRqhJlWdah1qCeTy',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            15 => 
            array (
                'id' => 16,
                'username' => 'NCA-0705',
                'email' => 'vincentleecrappy@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$AewzuyR35rB107qUzWvNruUPT0GQVmRJUy5FmJ0LehekmhP6FTr2K',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            16 => 
            array (
                'id' => 17,
                'username' => 'AEA-0710',
                'email' => 'arman.aquino.35@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$d5pWoMZkcsE2yZXvqpegzuSRsnxx.zAXgtfxz0mNTp4Oc6Lp7.aaG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            17 => 
            array (
                'id' => 18,
                'username' => 'GAA-1122',
                'email' => 'gretchelleatilano@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$X6P5fftzzp4wCiJbOIeE6uTvtDJhRrwO/B5tnw0wzFMlWaYfOvCBG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            18 => 
            array (
                'id' => 19,
                'username' => 'RRA-1114',
                'email' => 'rra-1114@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$iG5SLdRdoYqYUC2UNAbhpeFX1hOJ6IauGysrMbDe1cj7bNnd2.Lti',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            19 => 
            array (
                'id' => 20,
                'username' => 'NTA-1119',
                'email' => 'protein63nt@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QX0G/otJdlJtaF4ZAsZjXOZKu2WCEnr.ALGissyLFjHR1jGDQHuwS',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            20 => 
            array (
                'id' => 21,
                'username' => 'MRA-1218',
                'email' => 'ninimarielleatilano@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$fZvA8ZPYjiaHSRBgtXBgneCY3clOhCKObCN/ZZ.8TDPNQF80o3r8G',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            21 => 
            array (
                'id' => 22,
                'username' => 'JJB-1203',
                'email' => 'jali_badiola2005@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$5pYezoGkR.ZMZcGdZY1eseW1kifgYVRxbO8pTtuuvt3lPfMnYom5u',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            22 => 
            array (
                'id' => 23,
                'username' => 'CMB-0322',
                'email' => 'charisabaitit@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$y/xJ2GL6XC2wMNmANZWdAe303QmTFZqeZQLclDBtj6dqSkeCMcrma',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            23 => 
            array (
                'id' => 24,
                'username' => 'TBB-1204',
                'email' => 'mystara.mballa@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FEXH/CnKJ6HISXXbCtE5IOic6eBd.5rW7/SMqyS7xqRMlMUhpoG6y',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            24 => 
            array (
                'id' => 25,
                'username' => 'MJB-0401',
                'email' => 'markjayson181@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$C7kTnP8dHckxW4FKrRimj.yyHAfOGyykH.Ya2ESnzzHUZ3c.24.S2',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            25 => 
            array (
                'id' => 26,
                'username' => 'DSB-1118',
                'email' => 'dsb-1118@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YcuyUM3AbhlY8xl4FO7v6O4qSJwOsZAHjIwk0FpkuSU.wPkxqdN0K',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            26 => 
            array (
                'id' => 27,
                'username' => 'JOB-0518',
                'email' => 'jelynobayonas@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Uqp/JecFJOL6MMH2XuK4V.oWYdRISIDt/mrKkK4h/X37k7ExSayhO',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            27 => 
            array (
                'id' => 28,
                'username' => 'BBB-0703',
                'email' => 'bernadettebucoybelamide@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$A5w7i7FBBtjFXZaXO2nWn.1mYc8RUU84lqmgA/OcZ5IZL.1oIfk0a',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            28 => 
            array (
                'id' => 29,
                'username' => 'KVB-1227',
                'email' => 'kcbender97@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZneRj8QkwRH/awnfJPA9HONJah0SfiTl7Uu1l1VEryAsjSMS3Qdhe',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            29 => 
            array (
                'id' => 30,
                'username' => 'EOB-0415',
                'email' => 'Elijahbernales102713@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$TKBK9jikF0v4UkLmquCKcuhuTbKDH0HiW0XH3eWXrOQaJFaPKAD3K',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 1,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:07:49',
            ),
            30 => 
            array (
                'id' => 31,
                'username' => 'GJB-0630',
                'email' => 'gladysb.1224@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$sMHM73QvoUI8WKNAqVaHDe/3yEMwhbu/s1uqj4QOSWBzLvKyNb9j6',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            31 => 
            array (
                'id' => 32,
                'username' => 'SSB-1121',
                'email' => 'bernardosheila21@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6u50vmOS/SLSfot8elkjquFiK50zTItXlqAeEsj3nUx2XCXnaOR8m',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            32 => 
            array (
                'id' => 33,
                'username' => 'CGB-0323',
                'email' => 'cgb-0323@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$C2ih4vt6KkkYO6t3JjH71OBcfeRaqq2d4rLYahpygct.7j8j1blgW',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            33 => 
            array (
                'id' => 34,
                'username' => 'MCB-0107',
                'email' => 'marilynannbueno@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CCYgGJC.R.tK3gbtkELSPurW0HUFJM5QVU8RSy8s1hOtQq8W/qDky',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            34 => 
            array (
                'id' => 35,
                'username' => 'SLB-0611',
                'email' => 'slbdost9zc@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GAbGoBPy.uuMC2CV11evsuVxuQOKzTvIDsMVil1yzGaTf1W69BcS.',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            35 => 
            array (
                'id' => 36,
                'username' => 'OJB-0813',
                'email' => 'ojb-0813@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ABT8z1zkg2R5ed68hW2P1OHy1hgztAXwOvTzJpBZS1Q17jyLLdEEy',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            36 => 
            array (
                'id' => 37,
                'username' => 'JDC-0605',
                'email' => 'jhaykhaycee@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$N80WmzeEI7LDKHQtt0tapes4gEUlwFj1XKSyOcBelr2opJ/IuvrW.',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            37 => 
            array (
                'id' => 38,
                'username' => 'CLC-0818',
                'email' => 'iamechengg18@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$5eLvvseRsg0IFfkb5MFS0ue7YbYA9G5/79/KYND.gqR9kxp2wkbPy',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            38 => 
            array (
                'id' => 39,
                'username' => 'MGC-0312',
                'email' => 'cachinmarc@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Q4tHDiP88nyIwkIu/ESKReIr8fiGCKAqGVZhohgXY.V/T0FWdte.e',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            39 => 
            array (
                'id' => 40,
                'username' => 'DBC-0220',
                'email' => 'dorzmacau12@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$iSKXFMSPrTbdJct6YVODPOvu2T0rCvbnL.DMe1oNdNdCGg51fLow.',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            40 => 
            array (
                'id' => 41,
                'username' => 'KRC-0108',
                'email' => 'kcarumba043@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cFGJwqi9tdc/s3tvhTV0LO3AC4Er.IJ5o1OSER/511dWZpAKW69ku',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            41 => 
            array (
                'id' => 42,
                'username' => 'LDC-0325',
                'email' => 'N?A',
                'email_verified_at' => NULL,
                'password' => '$2y$10$29mrhRNzpaQQb50Ffzzby.88aO.lftpJ.9ltYVr5M3L557KRxqL6G',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            42 => 
            array (
                'id' => 43,
                'username' => 'TMC-0515',
                'email' => 'teffaniecatalya@yahoo.com.ph',
                'email_verified_at' => NULL,
                'password' => '$2y$10$c9in05k4qnC/sQr1WCzpYOOfF0KhV/gMll21Uv8ZGSLdFCEFGcePC',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            43 => 
            array (
                'id' => 44,
                'username' => 'ECC-0515',
                'email' => 'raincelorico@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7Q2GlSM2tzcMdAPglNLCueJZ6yxQNGLJPGq89oMtNpFBw7fgU2.NG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            44 => 
            array (
                'id' => 45,
                'username' => 'BTC-0913',
                'email' => 'b.cutara@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$PnfB5T98s3/tkwUbmKH0NejjkcwOX094Nl4KXN3vVP/0A5aGb.Cu6',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            45 => 
            array (
                'id' => 46,
                'username' => 'JMD-0111',
                'email' => 'dagoyjeaneanne@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$pzHqqneOFhm6pcjEU55B4.Ym5W/GVJ5.sensTtJWh7RtsLUDgd.6S',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            46 => 
            array (
                'id' => 47,
                'username' => 'JZD-0318',
                'email' => 'jervesdalde@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$In5syeWdjRYLdXBPSkpla.iaXv97SNex3uroxKrVYCGg2C58rVMVW',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            47 => 
            array (
                'id' => 48,
                'username' => 'MDD-0611',
                'email' => 'md3ph@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Y.oOhxhl4FYb4ZkQ3RxNduI3gNwzpJ/moI2UeR2ZT5KYfHv1iqUCS',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            48 => 
            array (
                'id' => 49,
                'username' => 'TED-0417',
                'email' => 'tediego@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$SZdJKQwDMWTsgyRBlkayFeMmNkGWR39FJOlBNLO5AOcf6sDB9bchC',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            49 => 
            array (
                'id' => 50,
                'username' => 'RRD-0613',
                'email' => 'rrd-0613@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$mUvP1c.BHkvBgdAcwKsEeuzPqadAr2dihw9gjRK6ojmHQi.ScgKqO',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            50 => 
            array (
                'id' => 51,
                'username' => 'JSD-1006',
                'email' => 'gienujsodiod@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$2vLYBuB9iCS5FibG/UA9NuXW0vuuwB9SleFRFSF3Hyn6RMlMpNhnG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            51 => 
            array (
                'id' => 52,
                'username' => 'JYE-0624',
                'email' => 'Johnkenesmas@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YXNrjNSSYqf/psaddXUis.YvPfVbKvvyrtM3whB1gn5bTAAn69yYa',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            52 => 
            array (
                'id' => 53,
                'username' => 'MRE-1014',
                'email' => 'melodrino60@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wa9mB5ssVgQnvtzaZoQjsupJojrpRg724B6LDtdhpRpIXk6Z.YZ5q',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            53 => 
            array (
                'id' => 54,
                'username' => 'AAF-0206',
                'email' => 'aaf-0206@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ImXyOXifHC19.rab/QZmiealvkEcQfEzDubiT09Aq6u75yPluFOUO',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            54 => 
            array (
                'id' => 55,
                'username' => 'JTF-0723',
                'email' => 'schezzo_july@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$f6NJTqRPV.bBsa6a4pm2TOZFn443/lV000z56vxCwakvXpmXSiYMi',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            55 => 
            array (
                'id' => 56,
                'username' => 'FLG-0827',
                'email' => 'flgalabin3@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JT2IVc5noXmjgMxjupKhquROAcn2.ppkeklLJ4nnaO.MM7rKq/1pu',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            56 => 
            array (
                'id' => 57,
                'username' => 'IIG-1106',
                'email' => 'ghazaliismael6@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$upfA3izsagSS3vVv4/I1n.vLc1V6gJMtbR3kYH.tJ91Ifnlg/Qhc6',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            57 => 
            array (
                'id' => 58,
                'username' => 'JRG-0730',
                'email' => 'jguinea78@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1vmsMsvDTViBnlS36j4nD..yLM7gjFSd8Lsjlo7qxnPJfFa3yEP86',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            58 => 
            array (
                'id' => 59,
                'username' => 'RBG-0110',
                'email' => 'ronnelg10@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KCJfuHKmAAIYndPoryU/M.LZ/Amye9OXer/tQb7ypq9VPKEWlfreq',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            59 => 
            array (
                'id' => 60,
                'username' => 'ASH-0501',
                'email' => 'arleneherbieto@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NrGwo/xTBjMZ00eNaoetV.LArBgi2G1fFcoeXQUDjmU7OEq.EbxzG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            60 => 
            array (
                'id' => 61,
                'username' => 'SFJ-0919',
                'email' => 'jovenal.sheryl@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$L.cUyXEyBwfSCeIqQVbtBe3MGoe.dPm.OJxAlYnFAVkikeKa10Pv2',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            61 => 
            array (
                'id' => 62,
                'username' => 'NJJ-0427',
                'email' => 'julwadi13@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$yfkUNu3huLqykSYs9/DrZumXzDJ6IX4GQPI.QRF2ZsRPrvARSJG3S',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            62 => 
            array (
                'id' => 63,
                'username' => 'RIJ-0311',
                'email' => 'kradjumli@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZVVSltQBXLkgxcTNW4qSWuEB4eZn8xDhSkdQnzuXfjrHWwT/ENSFm',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 1,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:08:41',
            ),
            63 => 
            array (
                'id' => 64,
                'username' => 'MLK-0526',
                'email' => 'mlk0526@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3dZaVjy4vbFqgTPcmPqH3OyI1u51TI4toDkGLrX.UZewISy6jgY22',
                'avatar' => 'avatar.jpg',
                'role' => 'Assistant Regional Director',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            64 => 
            array (
                'id' => 65,
                'username' => 'APL-0318',
                'email' => 'apl-0318@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$asVjgwpLem7vCXmV9V6MN.pxdaViymeHmt9ieDvemyCIpQH5SIYFa',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            65 => 
            array (
                'id' => 66,
                'username' => 'LGL-1112',
                'email' => 'loiserayleona@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VMIfdv4rh109FieaubvG2OTvXGegJYNWJLUObqUfFTGxJ9BmqhoUq',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 1,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:08:13',
            ),
            66 => 
            array (
                'id' => 67,
                'username' => 'RML-1114',
                'email' => 'rml-1114@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$v8Ix1qgxBK8O.gbSnKrYp.FUkzzVrKcwrdDsh4jJpN2toUbTURaty',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            67 => 
            array (
                'id' => 68,
                'username' => 'RML-1005',
                'email' => 'rubenjr1005@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$vyMzaHWjUmsN/LVMKq/XpuZet1NWKeV4LUr6MyYuBnuOVnnePSPTu',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            68 => 
            array (
                'id' => 69,
                'username' => 'RPM-1117',
                'email' => 'rickymahilum@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$w8jN2A7GxevSaZrormpNxemwLU1znNy71R5SV4cO8u7H/qCNr0nVu',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            69 => 
            array (
                'id' => 70,
                'username' => 'EMM-0715',
                'email' => 'emm-0715@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/pUmlMLxgexZKiF1.iFkdO8gNz.As4QKaFfEH3WGQilfa4maUhdfS',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            70 => 
            array (
                'id' => 71,
                'username' => 'JMM-0216',
                'email' => 'engr_jot@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eYxuVYL33Fni9h.iQj8EPe6kERvqOLWq2nEWx9Kxprz0T498v8Gl2',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            71 => 
            array (
                'id' => 72,
                'username' => 'SVM-0828',
                'email' => 'sharmainemorales28@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$uF4GdZEoYpJ3JdUcXVoXSOf.BEQoptLPyQQcCzBFe6Ze8qVvQM4kK',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            72 => 
            array (
                'id' => 73,
                'username' => 'ADM-0808',
                'email' => 'red_x88@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VfLMh6Vk9Yo1uUTrDsVUFO5Y51wCUAbawoagEmTazhV1.bx5Yb6.C',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            73 => 
            array (
                'id' => 74,
                'username' => 'MIM-1105',
                'email' => 'sidiako@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QDq7pateeUw02hFESjJlfOocBkoVNWOlXIWGAoqglT2NOvHcsQnZi',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            74 => 
            array (
                'id' => 75,
                'username' => 'JBN-0806',
                'email' => 'jpine652001@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ic.4w0ZY.M//oiwV4WI90erzIj.C9e7rCvQWt1eJkt81j3XxmpFfW',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            75 => 
            array (
                'id' => 76,
                'username' => 'JTO-0418',
                'email' => 'eriochromebt@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$t1hPFC9rXpc9LwHEFUQCJem89.ZGBezHJaq1J3A9n1wiZclvwOAYS',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            76 => 
            array (
                'id' => 77,
                'username' => 'BAP-0523',
                'email' => 'bonpadayhag@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6qpH103m8Je7ea3vGUiUJ.rst1n3eh9N4Hm8SnZbasLqTSE7N4G/y',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            77 => 
            array (
                'id' => 78,
                'username' => 'GFP-0608',
                'email' => 'pager57@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$k/ff0E9sEHB6kDmGpj9GqOsVW1nvZHvCAxrZSrkaYqJAGN/fh4ZNm',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            78 => 
            array (
                'id' => 79,
                'username' => 'EAP-1011',
                'email' => 'emapendergat95@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.4Ns4L/pLnRJoGZPiQRPT.gX4nQbevUITJHKnJBkFok1yFAbQg2YG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            79 => 
            array (
                'id' => 80,
                'username' => 'NGP-0321',
                'email' => 'njpjoepads@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/BXp0jVmiBXdqSWCbgnc3e5razw7lLULw8FDSXLmjclqDHoOvyDRy',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            80 => 
            array (
                'id' => 81,
                'username' => 'JAP-0108',
                'email' => 'japidor@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ObzMC91Aa/rKzIffBiZ.DORtNcTah6Smo40PzfIOiAY456cWl2IGu',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            81 => 
            array (
                'id' => 82,
                'username' => 'CBP-1205',
                'email' => 'crisprieto05@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Y6iWF4wtkkDiYjzZ69PVceHzeqBUyMZ.ZdSJKA4veJRLAp5O8ygru',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            82 => 
            array (
                'id' => 83,
                'username' => 'CLQ-1214',
                'email' => 'carlosyl_quinte@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$mKgg9xcNPgF3tcgqW5ppfOWuVJ9XbYNAzUO0BbVO8KrmTyESonRQW',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            83 => 
            array (
                'id' => 84,
                'username' => 'KRR-1109',
                'email' => 'kevinkarlramosramiso@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6Ci/e8eSef.k4p/CNC35A.SHYHsTFLTKNYfs8Zugokp0gAAUSPAcW',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            84 => 
            array (
                'id' => 85,
                'username' => 'JSR-0403',
                'email' => 'jemzremillete@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$finMk6NCZ4VAIqOlX8ugQ.Mctr2rxq4wELIy.hwwUYWgrJN0IAPDG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            85 => 
            array (
                'id' => 86,
                'username' => 'CRR-0918',
                'email' => 'cc.rawr.07@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0OuOgDBqGYktTgiPivqSxe0knizpaKg3YHxz9p6U9qp6Nk.M88mlG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            86 => 
            array (
                'id' => 87,
                'username' => 'JER-1231',
                'email' => 'jer-1231@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$F3ycytgmJj7srpZziPc3v.tkgWjAGImJDCZ02S6GaYZsS9TeGWa.6',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            87 => 
            array (
                'id' => 88,
                'username' => 'SAR-0110',
                'email' => 'sherylerico07@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$M/v26Mn4fAWiU5lYYrasE.BOYZiCgpLPTPFqcEFepC5goHPMDSNEi',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            88 => 
            array (
                'id' => 89,
                'username' => 'ALS-0205',
                'email' => 'analynsajiin@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$8bH6euOajnQ95PwBeGfuw.DyAmRVloC0VsBS23v4EjESblDP3abPG',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            89 => 
            array (
                'id' => 90,
                'username' => 'RSS-1204',
                'email' => 'rosemarie.salazar@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cT3z5KvtQvyhP0pxqTWNC.dmenIljlIWYPQKPI/MF7ktyGlKQNrD6',
                'avatar' => 'avatar.jpg',
                'role' => 'Assistant Regional Director',
                'is_active' => 1,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:07:35',
            ),
            90 => 
            array (
                'id' => 91,
                'username' => 'ACS-0415',
                'email' => 'anthonysantos77@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.oUkJ1RrzWHEbGT4orzU8O.zN00xALGJzOVZRroVXJemC77hR/UhW',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            91 => 
            array (
                'id' => 92,
                'username' => 'ABS-0530',
                'email' => 'aljeffrey.sardan30@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$beUENUKIaNpAr.dyEgs/1eQ1.yRJ23WJzCDpcgQ.xkkRvZVhhrn8.',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            92 => 
            array (
                'id' => 93,
                'username' => 'KRS-0127',
                'email' => 'kristinemaesarita27@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$dP6dfrFiEho1YRPxOvMFLu9tfQm/GXdZVUieGrFu8UTc257iJEaya',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            93 => 
            array (
                'id' => 94,
                'username' => 'SES-0118',
                'email' => 'suganobshadam@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wC7BmJqvGQEhTCWEaLH7r.QcB3/yd9cZUtnDWr6mO9oqmkXu9F4Ge',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 1,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:08:26',
            ),
            94 => 
            array (
                'id' => 95,
                'username' => 'DPS-0615',
                'email' => 'dreamlysumangil@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0sWBFjMeQfWwdf9hvGPxYOSm3PYw6s/uEzNszNEwWg9ajjFx9sX7e',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            95 => 
            array (
                'id' => 96,
                'username' => 'FSS-1121',
                'email' => 'jynx21.fs@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$d9VCtocCZ2A66tqKIoqCd.6o1PDFsjG04ZKdlDS1i/vRY..ZdqSYq',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            96 => 
            array (
                'id' => 97,
                'username' => 'BJT-0414',
                'email' => 'bjt-0414@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$j7ATym8Sj1dO437ShGKV9.TBewS9N8jEm1djC9OVFVBvte6D55M5O',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            97 => 
            array (
                'id' => 98,
                'username' => 'JBT-0716',
                'email' => 'jayceetangon@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$N0xLHFlc4wkdzsksHftlO.ppSo.exLN5Guy.te.R.2MZVtIHPK43u',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            98 => 
            array (
                'id' => 99,
                'username' => 'FTT-0620',
                'email' => 'melanietemonio@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$M2P4wTQvd38FucUxiTgNXuLzJAXQY54pzTw0uZj82OXnVXVuBVFCC',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            99 => 
            array (
                'id' => 100,
                'username' => 'JAT-0920',
                'email' => 'torresjames15@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JTgcCQK0ZuYIvNNRZ9imR.CCJ.511GewoOCl/ocy5G8o/lHPNCWxK',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            100 => 
            array (
                'id' => 101,
                'username' => 'JDV-0703',
                'email' => '123janmelvin@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$uwAdJ17.NzpjjGACi8RoMeE3LMf1Ntc6jylmxEG/z.dxxvR5Fewhq',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            101 => 
            array (
                'id' => 102,
                'username' => 'MAW-0302',
                'email' => 'mawee65@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$K3kjYANVO9NH1Wm0CTpd6./KEG3upw7.sGDgoLAeknJCwIkNUcc/i',
                'avatar' => 'avatar.jpg',
                'role' => 'Regional Director',
                'is_active' => 1,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:07:24',
            ),
            102 => 
            array (
                'id' => 103,
                'username' => 'ERZ-0614',
                'email' => 'eduzaragozajr@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$U5Br27ApFTpVGqJ6kGacXOK7HLurj9biNjBbXk5szdn1p2ky8DEGm',
                'avatar' => 'avatar.jpg',
                'role' => 'Employee',
                'is_active' => 0,
                'welcome_valid_until' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:06:55',
            ),
        ));
        
        
    }
}