<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_profiles')->delete();
        
        \DB::table('user_profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'firstname' => 'Ra-ouf',
                'lastname' => 'Jumli',
                'middlename' => 'Indanan',
                'suffix' => NULL,
                'gender' => 'Male',
                'mobile' => '09557650801',
                'birthday' => '1994-03-11',
                'address' => 'n/a',
                'user_id' => 1,
                'created_at' => '2022-12-20 21:06:09',
                'updated_at' => '2022-12-20 21:06:09',
            ),
            1 => 
            array (
                'id' => 2,
                'firstname' => 'Roberto',
                'lastname' => 'Abella',
                'middlename' => 'Bautista',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09174381331',
                'birthday' => '1957-12-23',
                'address' => 'B3 L8 Santiago Village, Divisoria, Zamboanga City',
                'user_id' => 2,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            2 => 
            array (
                'id' => 3,
                'firstname' => 'Ingrid',
                'lastname' => 'Abella-Colcol',
                'middlename' => 'Tagaro',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09954331808',
                'birthday' => '1981-01-07',
                'address' => '40-A Alejo Alvarez Street Zamboanga City',
                'user_id' => 3,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            3 => 
            array (
                'id' => 4,
                'firstname' => 'Gian Carlo',
                'lastname' => 'Acejas',
                'middlename' => 'Castillo',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09050633300',
                'birthday' => '1998-10-29',
                'address' => 'Guiwan, Zamboanga City',
                'user_id' => 4,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            4 => 
            array (
                'id' => 5,
                'firstname' => 'Herma Joyce',
                'lastname' => 'Alburo',
                'middlename' => 'Triambulo',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09057490947',
                'birthday' => '1989-03-16',
                'address' => 'Unit 8. TIU Apartment, Magsaysay Street., Brgy. Miputak, Dipolog',
                'user_id' => 5,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            5 => 
            array (
                'id' => 6,
                'firstname' => 'Stenel Rizza',
                'lastname' => 'Alegre',
                'middlename' => 'Villanueva',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09156383457',
                'birthday' => '1994-03-08',
                'address' => 'Kalantas Street, Zone 7-A, Zambowood , Zamboanga City',
                'user_id' => 6,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            6 => 
            array (
                'id' => 7,
                'firstname' => 'Merly',
                'lastname' => 'Alivio',
                'middlename' => 'Dalinsog',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09755640321',
                'birthday' => '1981-02-06',
                'address' => 'Zone 5, Boalan, Zamboanga City,',
                'user_id' => 7,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            7 => 
            array (
                'id' => 8,
                'firstname' => 'Nuhman',
                'lastname' => 'Aljani',
                'middlename' => 'Mahang',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09175119044',
                'birthday' => '1984-06-01',
                'address' => '',
                'user_id' => 8,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            8 => 
            array (
                'id' => 9,
                'firstname' => 'Judilyn',
                'lastname' => 'Alvarez',
                'middlename' => 'Enoferio',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09953275424',
                'birthday' => '1991-11-24',
                'address' => 'Lumiyap, Divisoria, Zamboanga City',
                'user_id' => 9,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            9 => 
            array (
                'id' => 10,
                'firstname' => 'Wilfredo',
                'lastname' => 'Alvarez',
                'middlename' => 'Paira',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09269557259',
                'birthday' => '1968-07-18',
                'address' => 'Carmen St, PC Compound, Zamboanga City',
                'user_id' => 10,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            10 => 
            array (
                'id' => 11,
                'firstname' => 'Jovita',
                'lastname' => 'Amparo',
                'middlename' => 'Apduhan',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09178389064',
                'birthday' => '1962-06-15',
                'address' => 'L-29, B-3 Carmen Valley Subd.,',
                'user_id' => 11,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            11 => 
            array (
                'id' => 12,
                'firstname' => 'Sheila',
                'lastname' => 'Andos',
                'middlename' => 'Bautista',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09176347500',
                'birthday' => '1985-08-01',
                'address' => '66-B Estrada St., Tetuan, Zamboanga City',
                'user_id' => 12,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            12 => 
            array (
                'id' => 13,
                'firstname' => 'Zoren',
                'lastname' => 'Antonio',
                'middlename' => 'Fabile',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09958418776',
                'birthday' => '1992-03-12',
                'address' => 'Hawaii Drive, Talon- Talon, Zamboanga City',
                'user_id' => 13,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            13 => 
            array (
                'id' => 14,
                'firstname' => 'Jeyzel',
                'lastname' => 'Aparri',
                'middlename' => 'Perez',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09778202436',
                'birthday' => '1986-11-01',
                'address' => 'J- Jireh Ice Plant Comp., Veterans Vill. Zamboanga Sibugay',
                'user_id' => 14,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            14 => 
            array (
                'id' => 15,
                'firstname' => 'Ricardo III',
                'lastname' => 'Apolinario',
                'middlename' => 'Jaldon',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09177085181/ 09',
                'birthday' => '1988-06-24',
                'address' => 'Zone 8, Daisy Road, Guiwan, Zamboanga City',
                'user_id' => 15,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            15 => 
            array (
                'id' => 16,
                'firstname' => 'Norie Vincent',
                'lastname' => 'Aposaga',
                'middlename' => 'Castro',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09279762262',
                'birthday' => '1993-07-05',
                'address' => 'Ipil Heigths, Ipil, Zamboanga Sibugay',
                'user_id' => 16,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            16 => 
            array (
                'id' => 17,
                'firstname' => 'Arman',
                'lastname' => 'Aquino',
                'middlename' => 'Elogsong',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09358099397',
                'birthday' => '1992-07-10',
                'address' => 'Timan, Liloy, Zamboanga del Norte',
                'user_id' => 17,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            17 => 
            array (
                'id' => 18,
                'firstname' => 'Gretchelle',
                'lastname' => 'Araneta',
                'middlename' => 'Atilano',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09152540342',
                'birthday' => '1988-11-22',
                'address' => 'Manicahan, Zamboanga City',
                'user_id' => 18,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            18 => 
            array (
                'id' => 19,
                'firstname' => 'Richard',
                'lastname' => 'Araneta',
                'middlename' => 'Rojas',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09265430256',
                'birthday' => '1971-11-14',
                'address' => '',
                'user_id' => 19,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            19 => 
            array (
                'id' => 20,
                'firstname' => 'Noel',
                'lastname' => 'Arquiza',
                'middlename' => 'Toh',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09262142321',
                'birthday' => '1963-11-19',
                'address' => '5-D Sto. Niño, San Jose, Zamboanga City',
                'user_id' => 20,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            20 => 
            array (
                'id' => 21,
                'firstname' => 'Marielle',
                'lastname' => 'Atilano',
                'middlename' => 'Ramirez',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09951548865',
                'birthday' => '1996-12-18',
                'address' => 'Froilano Alfaro Drive, Culianan, Zamboanga City',
                'user_id' => 21,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            21 => 
            array (
                'id' => 22,
                'firstname' => 'Jali',
                'lastname' => 'Badiola',
                'middlename' => 'Jamandre',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09177183644',
                'birthday' => '1962-12-03',
                'address' => 'Datiles Drv. Southcom Vill., Calarian, Zamboanga City',
                'user_id' => 22,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            22 => 
            array (
                'id' => 23,
                'firstname' => 'Charisa Mae',
                'lastname' => 'Bait-it',
                'middlename' => 'Malig-on',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09268545574',
                'birthday' => '1995-03-22',
                'address' => 'Baliwasan, Zamboanga City',
                'user_id' => 23,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            23 => 
            array (
                'id' => 24,
                'firstname' => 'Tara Mae',
                'lastname' => 'Balla',
                'middlename' => 'Burillo',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09268487084',
                'birthday' => '1985-12-04',
                'address' => '187 Hipolito Drive, San Roque, Zamboanga City',
                'user_id' => 24,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            24 => 
            array (
                'id' => 25,
                'firstname' => 'Mark Vincent',
                'lastname' => 'Baliña',
                'middlename' => 'Jayson',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09066430769',
                'birthday' => '1995-04-01',
                'address' => 'Sta. Clara, Lamitan City, Basilan',
                'user_id' => 25,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            25 => 
            array (
                'id' => 26,
                'firstname' => 'Danilo',
                'lastname' => 'Bation',
                'middlename' => 'Sajulan',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09553448119',
                'birthday' => '1969-11-18',
                'address' => 'Pasonanca, Luyahan, Zamboanga City',
                'user_id' => 26,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            26 => 
            array (
                'id' => 27,
                'firstname' => 'Jelyn',
                'lastname' => 'Bayonas',
                'middlename' => 'Octobre',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09105689314',
                'birthday' => '1990-05-18',
                'address' => 'Laoy Olingan, Dipolog City',
                'user_id' => 27,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            27 => 
            array (
                'id' => 28,
                'firstname' => 'Bernadette',
                'lastname' => 'Belamide',
                'middlename' => 'Bucoy',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09178315838',
                'birthday' => '1986-07-03',
                'address' => 'Zone 8, Calle Pilar, Ayala, Zamboanga City',
                'user_id' => 28,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            28 => 
            array (
                'id' => 29,
                'firstname' => 'Keanu Ceasar',
                'lastname' => 'Bender',
                'middlename' => 'Vics',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09951634026',
                'birthday' => '1997-12-27',
                'address' => 'Chinese Cemetery, San Roque, Zamboanga City',
                'user_id' => 29,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            29 => 
            array (
                'id' => 30,
                'firstname' => 'Elijah Denica',
                'lastname' => 'Bernales',
                'middlename' => 'Olasiman',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09356457392',
                'birthday' => '1998-04-15',
                'address' => '308 Talon-Talon, Logoy Diutay, Zamboanga City',
                'user_id' => 30,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            30 => 
            array (
                'id' => 31,
                'firstname' => 'Gladys',
                'lastname' => 'Bernardo',
                'middlename' => 'Jimeno',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09058323021',
                'birthday' => '1986-06-30',
                'address' => 'Sta. Maria, Pagadian City, Zamboanga del Sur',
                'user_id' => 31,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            31 => 
            array (
                'id' => 32,
                'firstname' => 'Sheila',
                'lastname' => 'Bernardo',
                'middlename' => 'Salenga',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09977151789',
                'birthday' => '1994-11-21',
                'address' => 'Purok 8, Barigon, Tugbungan, Zamboanga City',
                'user_id' => 32,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            32 => 
            array (
                'id' => 33,
                'firstname' => 'Cleypart',
                'lastname' => 'Braca',
                'middlename' => 'Geba',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09676545328',
                'birthday' => '2000-03-23',
                'address' => 'Tupilac R.T Lim, Zamboanga Sibugay',
                'user_id' => 33,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            33 => 
            array (
                'id' => 34,
                'firstname' => 'Marilyn Ann',
                'lastname' => 'Bueno',
                'middlename' => 'Caldito',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09069374034/ 09',
                'birthday' => '1981-01-07',
                'address' => 'Immaculate Drive, Culianan, Zamboanga City',
                'user_id' => 34,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            34 => 
            array (
                'id' => 35,
                'firstname' => 'Sonora',
                'lastname' => 'Buñag',
                'middlename' => 'Leonora',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09178494346',
                'birthday' => '1965-06-11',
                'address' => '',
                'user_id' => 35,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            35 => 
            array (
                'id' => 36,
                'firstname' => 'Omar',
                'lastname' => 'Butlangan',
                'middlename' => 'Jilhano',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09365273006',
                'birthday' => '1997-08-13',
                'address' => '',
                'user_id' => 36,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            36 => 
            array (
                'id' => 37,
                'firstname' => 'John Kenneth',
                'lastname' => 'Cabral',
                'middlename' => 'De Asis',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09177160242',
                'birthday' => '1991-06-05',
                'address' => '',
                'user_id' => 37,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            37 => 
            array (
                'id' => 38,
                'firstname' => 'Cyron',
                'lastname' => 'Caburnay',
                'middlename' => 'Liang',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09958544840',
                'birthday' => '1995-08-18',
                'address' => 'Casumpang Drive, San Jose Rd., ZC',
                'user_id' => 38,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            38 => 
            array (
                'id' => 39,
                'firstname' => 'Marc',
                'lastname' => 'Cachin',
                'middlename' => 'Guimbarda',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09773325701',
                'birthday' => '1984-03-12',
                'address' => '',
                'user_id' => 39,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            39 => 
            array (
                'id' => 40,
                'firstname' => 'Dores',
                'lastname' => 'Calago',
                'middlename' => 'Barnayja',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09102018828',
                'birthday' => '1988-02-20',
                'address' => 'TMI 4, Pangi, Ipil, Zamboanga Sibugay Province',
                'user_id' => 40,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            40 => 
            array (
                'id' => 41,
                'firstname' => 'Kim',
                'lastname' => 'Carumba',
                'middlename' => 'Ricaborda',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09364743457',
                'birthday' => '1996-01-08',
                'address' => 'Mabini, Titay, Zamboanga Sibugay',
                'user_id' => 41,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            41 => 
            array (
                'id' => 42,
                'firstname' => 'Leopoldo Jr.',
                'lastname' => 'Castillo',
                'middlename' => 'De Vera',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09069010003',
                'birthday' => '1971-03-25',
                'address' => 'Purok 4, Tugbungan, Zamboanga City',
                'user_id' => 42,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            42 => 
            array (
                'id' => 43,
                'firstname' => 'Teffanie Mae',
                'lastname' => 'Catalya',
                'middlename' => 'Madrazo',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09352070225',
                'birthday' => '1992-05-15',
                'address' => 'Perez Drive, San Roque, Zamboanga City',
                'user_id' => 43,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            43 => 
            array (
                'id' => 44,
                'firstname' => 'Edgar Rainier',
                'lastname' => 'Celorico',
                'middlename' => 'Carreon',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09554082366',
                'birthday' => '1986-05-15',
                'address' => '4 Don Francisco St., Brangy Sto. Niño, Zamboanga City',
                'user_id' => 44,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            44 => 
            array (
                'id' => 45,
                'firstname' => 'Bergel',
                'lastname' => 'Cutara',
                'middlename' => 'Tachado',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09171063708',
                'birthday' => '1994-09-13',
                'address' => 'Mangaya-ay Association, KM 7, Mampang, Zamboanga City',
                'user_id' => 45,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            45 => 
            array (
                'id' => 46,
                'firstname' => 'Jeane Anne',
                'lastname' => 'Dagoy',
                'middlename' => 'Mapa',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09672737257',
                'birthday' => '1992-01-11',
                'address' => 'Henso Subdivision, Cor. Esmeraldo Drive, Cabatangan, ZC',
                'user_id' => 46,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            46 => 
            array (
                'id' => 47,
                'firstname' => 'Jerves',
                'lastname' => 'Dalde',
                'middlename' => 'Zamora',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09957113251',
                'birthday' => '1993-03-18',
                'address' => 'Poblacion, Titay, Zamboanga Sibugay',
                'user_id' => 47,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            47 => 
            array (
                'id' => 48,
                'firstname' => 'Mariano III',
                'lastname' => 'Devasfruto',
                'middlename' => 'De Mesa',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09174230790',
                'birthday' => '1981-06-11',
                'address' => 'Raven Drive, Km 4., Pasonanca Zamboanga City',
                'user_id' => 48,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            48 => 
            array (
                'id' => 49,
                'firstname' => 'Thelma',
                'lastname' => 'Diego',
                'middlename' => 'Emata',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09175555924',
                'birthday' => '1966-04-17',
                'address' => 'Perez Drive, Guiwan, Zamboanga City',
                'user_id' => 49,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            49 => 
            array (
                'id' => 50,
                'firstname' => 'Ronie',
                'lastname' => 'Dinawanao',
                'middlename' => 'Ricablanca',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09103088365',
                'birthday' => '1977-06-13',
                'address' => '',
                'user_id' => 50,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            50 => 
            array (
                'id' => 51,
                'firstname' => 'Jungie',
                'lastname' => 'Diodos',
                'middlename' => 'Sangrenes',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09486886768',
                'birthday' => '1989-10-06',
                'address' => 'P-1 Villa Castor, Buug, Zamboanga Sibugay',
                'user_id' => 51,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            51 => 
            array (
                'id' => 52,
                'firstname' => 'John Ken',
                'lastname' => 'Esmas',
                'middlename' => 'Yamuta',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09171267984',
                'birthday' => '1995-06-24',
                'address' => 'Purok Makabibihag, Poblacion, Malangas, ZSP',
                'user_id' => 52,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            52 => 
            array (
                'id' => 53,
                'firstname' => 'Melodrino',
                'lastname' => 'Estabillo',
                'middlename' => 'Revilla',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09065323182',
                'birthday' => '1968-10-14',
                'address' => 'Purok 7, Cambodia Drive, Sangali, Zamboanga City',
                'user_id' => 53,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            53 => 
            array (
                'id' => 54,
                'firstname' => 'Armando',
                'lastname' => 'Fernandez',
                'middlename' => 'Anlas',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09098500712',
                'birthday' => '1981-02-06',
                'address' => 'Purok Tugas, Balangasan Dist. Pagadian City',
                'user_id' => 54,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            54 => 
            array (
                'id' => 55,
                'firstname' => 'Julius',
                'lastname' => 'Fojas',
                'middlename' => 'Taghap',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09177560264',
                'birthday' => '1987-07-23',
                'address' => 'Baliwasan, Zamboanga City',
                'user_id' => 55,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            55 => 
            array (
                'id' => 56,
                'firstname' => 'Fortunato',
                'lastname' => 'Galabin',
                'middlename' => 'Landicho',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09064417672',
                'birthday' => '1990-08-27',
                'address' => '114 Lucky Sunrise Drive, Tumaga, Zamboanga City',
                'user_id' => 56,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            56 => 
            array (
                'id' => 57,
                'firstname' => 'Ismael',
                'lastname' => 'Ghazali',
                'middlename' => 'Ismael',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09054586190',
                'birthday' => '1994-11-06',
                'address' => 'Block 9, Lot 37, Phase II, HB Homes, Sinunuc, Zamboanga City',
                'user_id' => 57,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            57 => 
            array (
                'id' => 58,
                'firstname' => 'Jenard Bert',
                'lastname' => 'Guinea',
                'middlename' => 'Retiza',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09618195990',
                'birthday' => '1996-07-30',
                'address' => 'Perez Drive, Putik, Zamboanga City',
                'user_id' => 58,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            58 => 
            array (
                'id' => 59,
                'firstname' => 'Ronnel',
                'lastname' => 'Gundoy',
                'middlename' => 'Baluan',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09266511082',
                'birthday' => '1983-01-10',
                'address' => '25-B Sto. Niño, Zamboanga City',
                'user_id' => 59,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            59 => 
            array (
                'id' => 60,
                'firstname' => 'Arlene',
                'lastname' => 'Herbieto',
                'middlename' => 'Sabalde',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09052279213',
                'birthday' => '1976-05-01',
                'address' => '36 Upper Calarian, Zamboanga City',
                'user_id' => 60,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            60 => 
            array (
                'id' => 61,
                'firstname' => 'Sheryl',
                'lastname' => 'Jovenal',
                'middlename' => 'Flores',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09778205540',
                'birthday' => '1989-09-19',
                'address' => 'Purok 5, Bayog, Zamboanga del Sur',
                'user_id' => 61,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            61 => 
            array (
                'id' => 62,
                'firstname' => 'Nursida Jamsuri',
                'lastname' => 'Julwadi',
                'middlename' => 'Jammang',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09056775194',
                'birthday' => '1990-04-27',
                'address' => 'Campo Muslim St., Tahir Drive, Rio Hondo, Zamboanga City',
                'user_id' => 62,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            62 => 
            array (
                'id' => 63,
                'firstname' => 'Ra-ouf',
                'lastname' => 'Jumli',
                'middlename' => 'Indanan',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09557650803',
                'birthday' => '1994-03-11',
                'address' => '4th Street, Aurora Village, Guiwan, Zamboanga City',
                'user_id' => 63,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            63 => 
            array (
                'id' => 64,
                'firstname' => 'Mahmud',
                'lastname' => 'Kingking',
                'middlename' => 'Lasola',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09173128701',
                'birthday' => '1958-05-26',
                'address' => 'B-3 L-3 Cooperative Village, Putik, Zamboanga City',
                'user_id' => 64,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            64 => 
            array (
                'id' => 65,
                'firstname' => 'Allan Geion',
                'lastname' => 'Legaspi',
                'middlename' => 'Pagayonan',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09272220224',
                'birthday' => '1973-03-18',
                'address' => '542-Billiard Drive, Baliwasan, Zamboanga City',
                'user_id' => 65,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            65 => 
            array (
                'id' => 66,
                'firstname' => 'Loise Ray',
                'lastname' => 'Leona',
                'middlename' => 'Garces',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09954332882',
                'birthday' => '1993-11-12',
                'address' => '2nd Navarro Drive, San Roque, Zamboanga City',
                'user_id' => 66,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            66 => 
            array (
                'id' => 67,
                'firstname' => 'Romeo',
                'lastname' => 'Ligalig',
                'middlename' => 'Montano',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09364374794',
                'birthday' => '1971-11-14',
                'address' => 'Galvez Drive, Sta. Maria, Zamboanga City',
                'user_id' => 67,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            67 => 
            array (
                'id' => 68,
                'firstname' => 'Ruben',
                'lastname' => 'Lim Jr',
                'middlename' => 'Matchon',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09152795426',
                'birthday' => '1986-10-05',
                'address' => 'Blk. 1 Lt. 13 Carmen Valley Subd. Pasonanca, Zamboanga City',
                'user_id' => 68,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            68 => 
            array (
                'id' => 69,
                'firstname' => 'Ricky',
                'lastname' => 'Mahilum',
                'middlename' => 'Palen',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09357310144',
                'birthday' => '1992-11-17',
                'address' => 'Don MC Enriquez Drive, Tetuan, Zamboanga City',
                'user_id' => 69,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            69 => 
            array (
                'id' => 70,
                'firstname' => 'Enrique',
                'lastname' => 'Mariano',
                'middlename' => 'Magnaye',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09068566550',
                'birthday' => '1966-07-15',
                'address' => 'Nieves F. Jose Drive, San Jose Gusu, Z.C',
                'user_id' => 70,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            70 => 
            array (
                'id' => 71,
                'firstname' => 'Jose Maria',
                'lastname' => 'Molina',
                'middlename' => 'Mendoza',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09178494278',
                'birthday' => '1959-02-16',
                'address' => '60 San Jose Gusu, Zamboanga City',
                'user_id' => 71,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            71 => 
            array (
                'id' => 72,
                'firstname' => 'Sharmaine',
                'lastname' => 'Morales',
                'middlename' => 'Villagracia',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09758301023',
                'birthday' => '1992-08-28',
                'address' => 'Acuña Drive, Tumaga, Zamboanga City',
                'user_id' => 72,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            72 => 
            array (
                'id' => 73,
                'firstname' => 'Aris',
                'lastname' => 'Moratalla',
                'middlename' => 'Despalo',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09274790425',
                'birthday' => '1982-08-08',
                'address' => 'Purok 8, Barigon, Tugbungan, Zamboanga City',
                'user_id' => 73,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            73 => 
            array (
                'id' => 74,
                'firstname' => 'Mulsidi',
                'lastname' => 'Mulsid',
                'middlename' => 'Ibrahim',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09205055819',
                'birthday' => '1995-05-11',
                'address' => '499A, Preza Drive, Camino Nuevo, ZC',
                'user_id' => 74,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            74 => 
            array (
                'id' => 75,
                'firstname' => 'Josephine',
                'lastname' => 'Nohay',
                'middlename' => 'Bejoc',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09758975638',
                'birthday' => '1965-08-06',
                'address' => '171-B Governor Alvarez Avenue, Zamboanga City',
                'user_id' => 75,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            75 => 
            array (
                'id' => 76,
                'firstname' => 'Janice',
                'lastname' => 'Ong',
                'middlename' => 'Tangcalagan',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09954332769',
                'birthday' => '1986-04-18',
                'address' => 'Lustre St. Sta. Catalina, Zamboanga City',
                'user_id' => 76,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            76 => 
            array (
                'id' => 77,
                'firstname' => 'Bon Rafael',
                'lastname' => 'Padayhag',
                'middlename' => 'Abilla',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09265440175',
                'birthday' => '1986-05-23',
                'address' => '221 Saavedra Ext., De Leon St., Sta. Maria, Zamboanga City',
                'user_id' => 77,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            77 => 
            array (
                'id' => 78,
                'firstname' => 'Gerardo',
                'lastname' => 'Parot',
                'middlename' => 'Fajardo',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09217631665',
                'birthday' => '1965-06-08',
                'address' => 'Blk 13 Lot1, Alta Tierra, Tiguma, Pagadian City',
                'user_id' => 78,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            78 => 
            array (
                'id' => 79,
                'firstname' => 'Ellyssa Mae',
                'lastname' => 'Pendergat',
                'middlename' => 'Agad',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09552730938',
                'birthday' => '1995-10-11',
                'address' => '512 Bouganvilla Lane, Tugbungan, Zamboanga City',
                'user_id' => 79,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            79 => 
            array (
                'id' => 80,
                'firstname' => 'Neil Joseph',
                'lastname' => 'Padao',
                'middlename' => 'Galera',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09952253073',
                'birthday' => '1994-03-21',
                'address' => 'Dr. Jose Rizal, Katipunan, Zamboanga del Norte',
                'user_id' => 80,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            80 => 
            array (
                'id' => 81,
                'firstname' => 'Jennifer',
                'lastname' => 'Pidor',
                'middlename' => 'Alcazar',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09177183645',
                'birthday' => '1984-01-08',
                'address' => 'Blk 5, Lot 18, Sto. Niño Village, Putik, Zamboanga City',
                'user_id' => 81,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            81 => 
            array (
                'id' => 82,
                'firstname' => 'Cris-Angelo',
                'lastname' => 'Prieto',
                'middlename' => 'Busania',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09262402398',
                'birthday' => '1990-12-05',
                'address' => 'A&W Subd. Block 1 Lot 32 Phase V, Putik, Zamboanga City',
                'user_id' => 82,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            82 => 
            array (
                'id' => 83,
                'firstname' => 'Carlo Syl',
                'lastname' => 'Quinte',
                'middlename' => 'Labuca',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09173592756',
                'birthday' => '1981-12-14',
                'address' => 'Purok Azucena, Kitabog, Titay, Zamboanga Sibugay',
                'user_id' => 83,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            83 => 
            array (
                'id' => 84,
                'firstname' => 'Kevin Karl',
                'lastname' => 'Ramiso',
                'middlename' => 'Ramos',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09451422986',
                'birthday' => '1994-11-09',
                'address' => 'Talungon, San Roque, Zamboanga City',
                'user_id' => 84,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            84 => 
            array (
                'id' => 85,
                'firstname' => 'Jerome',
                'lastname' => 'Remillete',
                'middlename' => 'Salvador',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09061593612',
                'birthday' => '1996-04-03',
                'address' => 'Sunsent View, Urban Poor, Cabatangan, Zamboanga City',
                'user_id' => 85,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            85 => 
            array (
                'id' => 86,
                'firstname' => 'Christian Carl',
                'lastname' => 'Resente',
                'middlename' => 'Rivera',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09778336488',
                'birthday' => '1993-09-18',
                'address' => 'Purok Marang, Tuburan, Pagadian City, Zamboanga del Sur',
                'user_id' => 86,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            86 => 
            array (
                'id' => 87,
                'firstname' => 'Jesus',
                'lastname' => 'Reyes',
                'middlename' => 'Ejansantos',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09658671849',
                'birthday' => '1954-12-31',
                'address' => 'Talon-Talon, Zamboanga City',
                'user_id' => 87,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            87 => 
            array (
                'id' => 88,
                'firstname' => 'Sheryle',
                'lastname' => 'Rico',
                'middlename' => 'Alferez',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09358268492',
                'birthday' => '1994-01-10',
                'address' => '247 Don Toribio St., Tetuan, Zamboanga City',
                'user_id' => 88,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            88 => 
            array (
                'id' => 89,
                'firstname' => 'Analyn',
                'lastname' => 'Sajiin',
                'middlename' => 'Lasola',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09058669674',
                'birthday' => '1992-02-05',
                'address' => 'Block 3, Lot 19, Blue Vista Subd., Ayala, Zamboanga City',
                'user_id' => 89,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            89 => 
            array (
                'id' => 90,
                'firstname' => 'Rosemarie',
                'lastname' => 'Salazar',
                'middlename' => 'Sinsuan',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09177224118',
                'birthday' => '1964-12-04',
                'address' => '',
                'user_id' => 90,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            90 => 
            array (
                'id' => 91,
                'firstname' => 'Anthony',
                'lastname' => 'Santos',
                'middlename' => 'Climaco',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09396070712',
                'birthday' => '1986-04-15',
                'address' => 'Calle San Isidro St. Mercedes, Zamboanga City',
                'user_id' => 91,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            91 => 
            array (
                'id' => 92,
                'firstname' => 'Al Jeffrey',
                'lastname' => 'Sardan',
                'middlename' => 'Bregondot',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09976143937',
                'birthday' => '1994-05-30',
                'address' => 'Masiay Pasay, San Roque,  Zamboanga City',
                'user_id' => 92,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            92 => 
            array (
                'id' => 93,
                'firstname' => 'Kristine Mae',
                'lastname' => 'Sarita',
                'middlename' => 'Rodriguez',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09454681800',
                'birthday' => '1991-01-27',
                'address' => 'De Leon St., Sta. Maria, Zamboanga City',
                'user_id' => 93,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            93 => 
            array (
                'id' => 94,
                'firstname' => 'Shadam',
                'lastname' => 'Suganob',
                'middlename' => 'Eroy',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09279203290',
                'birthday' => '1991-01-18',
                'address' => 'Montesino Drive, Sta. Maria, Zamboanga City',
                'user_id' => 94,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            94 => 
            array (
                'id' => 95,
                'firstname' => 'Dreamly',
                'lastname' => 'Sumangil',
                'middlename' => 'Pajarito',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09750881125',
                'birthday' => '1996-06-15',
                'address' => 'Poblacion, Titay, Zamboanga Sibugay',
                'user_id' => 95,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            95 => 
            array (
                'id' => 96,
                'firstname' => 'Florentino III',
                'lastname' => 'Susalo',
                'middlename' => 'Sagun',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09052485174',
                'birthday' => '1988-11-21',
                'address' => 'Love Drive, Pasy Masiay, San Roque, Zamboanga City',
                'user_id' => 96,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            96 => 
            array (
                'id' => 97,
                'firstname' => 'Benito',
                'lastname' => 'Tajada',
                'middlename' => 'Jucom',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09171160399',
                'birthday' => '1963-04-14',
                'address' => 'Canelar, Zamboanga City',
                'user_id' => 97,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            97 => 
            array (
                'id' => 98,
                'firstname' => 'Jun Carlo',
                'lastname' => 'Tangon',
                'middlename' => 'Ban-as',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09279347641',
                'birthday' => '1993-07-16',
                'address' => 'Mango Drive, Tumaga, Zamboanga City',
                'user_id' => 98,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            98 => 
            array (
                'id' => 99,
                'firstname' => 'Francis Melanie',
                'lastname' => 'Temonio',
                'middlename' => 'Taneza',
                'suffix' => NULL,
                'gender' => 'F',
                'mobile' => '09176248688',
                'birthday' => '1982-06-20',
                'address' => 'B6 l9, Nesoricom Village, Zamboanga Sibugay',
                'user_id' => 99,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            99 => 
            array (
                'id' => 100,
                'firstname' => 'James',
                'lastname' => 'Torres',
                'middlename' => 'Adis',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09559087469',
                'birthday' => '1994-09-20',
                'address' => 'Don Alfaro St., Tetuan, Zamboanga City',
                'user_id' => 100,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            100 => 
            array (
                'id' => 101,
                'firstname' => 'Jan Melvin',
                'lastname' => 'Vallejo',
                'middlename' => 'Dela Cruz',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09466109729',
                'birthday' => '1995-07-03',
                'address' => 'Manlabay, Dumingag, Zamboanga del Sur',
                'user_id' => 101,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:06:55',
            ),
            101 => 
            array (
                'id' => 102,
                'firstname' => 'Martin',
                'lastname' => 'Wee',
                'middlename' => 'Ausejo',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09178590382',
                'birthday' => '1965-03-02',
                'address' => 'L4 B5 Carmen Valley, Pasonanca, Zamboanga City',
                'user_id' => 102,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:06:55',
            ),
            102 => 
            array (
                'id' => 103,
                'firstname' => 'Eduardo Jr.',
                'lastname' => 'Zaragoza',
                'middlename' => 'Resurreccion',
                'suffix' => NULL,
                'gender' => 'M',
                'mobile' => '09750338303',
                'birthday' => '1984-06-14',
                'address' => '132 Veterans Avenue Extension, Sta. Maria, Zamboanga City',
                'user_id' => 103,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:06:55',
            ),
        ));
        
        
    }
}