<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserEmployeesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_employees')->delete();
        
        \DB::table('user_employees')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 2,
                'position_id' => 1,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '1996-03-05',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 3,
                'position_id' => 2,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 30,
                'start' => '2018-02-15',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 4,
                'position_id' => 3,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 26,
                'start' => '2021-04-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 5,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 9,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 29,
                'start' => '2021-11-23',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 6,
                'position_id' => 5,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2021-05-04',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 7,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 29,
                'start' => '2017-07-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 8,
                'position_id' => 6,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 9,
                'religion_id' => 16,
                'level_id' => 1,
                'blood_id' => 30,
                'start' => '2017-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 9,
                'position_id' => 7,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 1,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2020-03-02',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 10,
                'position_id' => 8,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 21,
                'blood_id' => 1,
                'start' => '1905-06-14',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 11,
                'position_id' => 9,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 1,
                'blood_id' => 29,
                'start' => '1992-06-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 12,
                'position_id' => 5,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2022-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 13,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2017-07-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 14,
                'position_id' => 6,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 11,
                'religion_id' => 15,
                'level_id' => 1,
                'blood_id' => 25,
                'start' => '2011-02-21',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 15,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 27,
                'start' => '2017-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 16,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2017-07-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 17,
                'position_id' => 7,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 9,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 1,
                'start' => '2020-03-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 18,
                'position_id' => 10,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 25,
                'start' => '2018-12-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:49',
                'updated_at' => '2022-12-20 21:06:49',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 19,
                'position_id' => 11,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 21,
                'blood_id' => 30,
                'start' => '1905-07-07',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 20,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 25,
                'start' => '2004-08-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 21,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2018-12-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 22,
                'position_id' => 12,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 24,
                'start' => '2003-01-20',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 23,
                'position_id' => 5,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 14,
                'level_id' => 19,
                'blood_id' => 25,
                'start' => '2020-02-17',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 24,
                'position_id' => 5,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 25,
                'start' => '2021-05-31',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 25,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2018-10-22',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 26,
                'position_id' => 13,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '1905-07-07',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 27,
                'position_id' => 6,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 9,
                'religion_id' => 18,
                'level_id' => 1,
                'blood_id' => 31,
                'start' => '2021-11-11',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 28,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 27,
                'start' => '2013-03-20',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 29,
                'position_id' => 14,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 1,
                'start' => '2022-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 30,
                'position_id' => 15,
                'department_id' => 2,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2022-04-04',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 31,
                'position_id' => 15,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 10,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2020-02-06',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 32,
                'position_id' => 5,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 25,
                'start' => '2016-04-06',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 33,
                'position_id' => 16,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 23,
                'blood_id' => 30,
                'start' => '2019-10-14',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 34,
                'position_id' => 17,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2008-03-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 35,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 24,
                'start' => '1991-12-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:50',
                'updated_at' => '2022-12-20 21:06:50',
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 36,
                'position_id' => 18,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 19,
                'blood_id' => 1,
                'start' => '2022-02-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 37,
                'position_id' => 6,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 10,
                'religion_id' => 13,
                'level_id' => 1,
                'blood_id' => 30,
                'start' => '2017-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 38,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2022-12-22',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 39,
                'position_id' => 6,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 9,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 24,
                'start' => '2017-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 40,
                'position_id' => 7,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 24,
                'start' => '2020-11-09',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 41,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2020-02-10',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 42,
                'position_id' => 19,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 23,
                'blood_id' => 30,
                'start' => '2020-02-17',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 43,
                'position_id' => 20,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 31,
                'start' => '2017-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 44,
                'position_id' => 21,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2019-04-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 45,
                'position_id' => 9,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 31,
                'start' => '2015-05-05',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 46,
                'position_id' => 4,
                'department_id' => 2,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 1,
                'blood_id' => 25,
                'start' => '2021-11-29',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 47,
                'position_id' => 7,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2022-01-19',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 48,
                'position_id' => 9,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 27,
                'start' => '2018-03-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 49,
                'position_id' => 22,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 20,
                'blood_id' => 26,
                'start' => '1989-09-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 50,
                'position_id' => 23,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 9,
                'religion_id' => 13,
                'level_id' => 21,
                'blood_id' => 1,
                'start' => '1905-06-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 51,
                'position_id' => 10,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2020-02-10',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 52,
                'position_id' => 10,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2021-01-11',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:51',
                'updated_at' => '2022-12-20 21:06:51',
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 53,
                'position_id' => 11,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 23,
                'blood_id' => 26,
                'start' => '1905-07-10',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 54,
                'position_id' => 24,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 10,
                'religion_id' => 13,
                'level_id' => 23,
                'blood_id' => 30,
                'start' => '2020-02-05',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 55,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 1,
                'blood_id' => 26,
                'start' => '2017-01-25',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 56,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 1,
                'blood_id' => 30,
                'start' => '2017-03-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 57,
                'position_id' => 5,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2021-12-08',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 58,
                'position_id' => 25,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2022-02-14',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 59,
                'position_id' => 12,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 20,
                'blood_id' => 30,
                'start' => '2010-12-30',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 60,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2001-09-26',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 61,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 10,
                'religion_id' => 14,
                'level_id' => 1,
                'blood_id' => 31,
                'start' => '2013-04-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 62,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 20,
                'blood_id' => 29,
                'start' => '2022-03-24',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 63,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 19,
                'blood_id' => 1,
                'start' => '2021-04-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 64,
                'position_id' => 26,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 1,
                'blood_id' => 24,
                'start' => '1984-05-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 65,
                'position_id' => 27,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 28,
                'start' => '2018-02-15',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 66,
                'position_id' => 28,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 31,
                'start' => '2017-03-22',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 67,
                'position_id' => 11,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 23,
                'blood_id' => 30,
                'start' => '1905-07-07',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:52',
                'updated_at' => '2022-12-20 21:06:52',
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 68,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 20,
                'blood_id' => 25,
                'start' => '2013-03-18',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 69,
                'position_id' => 5,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2020-02-13',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 70,
                'position_id' => 29,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 23,
                'blood_id' => 30,
                'start' => '1905-06-15',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 71,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 26,
                'start' => '1992-05-04',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 72,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2017-07-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 73,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 30,
                'start' => '2017-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            72 => 
            array (
                'id' => 73,
                'user_id' => 74,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2022-12-22',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            73 => 
            array (
                'id' => 74,
                'user_id' => 75,
                'position_id' => 30,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 26,
                'start' => '2007-11-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            74 => 
            array (
                'id' => 75,
                'user_id' => 76,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 30,
                'start' => '2017-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            75 => 
            array (
                'id' => 76,
                'user_id' => 77,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2019-11-21',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            76 => 
            array (
                'id' => 77,
                'user_id' => 78,
                'position_id' => 9,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 10,
                'religion_id' => 13,
                'level_id' => 1,
                'blood_id' => 24,
                'start' => '1992-12-10',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            77 => 
            array (
                'id' => 78,
                'user_id' => 79,
                'position_id' => 18,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 20,
                'blood_id' => 31,
                'start' => '2021-06-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            78 => 
            array (
                'id' => 79,
                'user_id' => 80,
                'position_id' => 15,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 9,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 28,
                'start' => '2022-10-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            79 => 
            array (
                'id' => 80,
                'user_id' => 81,
                'position_id' => 9,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 14,
                'level_id' => 1,
                'blood_id' => 25,
                'start' => '2007-11-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            80 => 
            array (
                'id' => 81,
                'user_id' => 82,
                'position_id' => 20,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 25,
                'start' => '2014-10-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            81 => 
            array (
                'id' => 82,
                'user_id' => 83,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 11,
                'religion_id' => 15,
                'level_id' => 1,
                'blood_id' => 31,
                'start' => '2014-08-18',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            82 => 
            array (
                'id' => 83,
                'user_id' => 84,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2019-05-15',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:53',
                'updated_at' => '2022-12-20 21:06:53',
            ),
            83 => 
            array (
                'id' => 84,
                'user_id' => 85,
                'position_id' => 10,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 25,
                'start' => '2020-08-17',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            84 => 
            array (
                'id' => 85,
                'user_id' => 86,
                'position_id' => 6,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 10,
                'religion_id' => 13,
                'level_id' => 20,
                'blood_id' => 30,
                'start' => '2013-04-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            85 => 
            array (
                'id' => 86,
                'user_id' => 87,
                'position_id' => 31,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 23,
                'blood_id' => 28,
                'start' => '2020-08-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            86 => 
            array (
                'id' => 87,
                'user_id' => 88,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2019-01-14',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            87 => 
            array (
                'id' => 88,
                'user_id' => 89,
                'position_id' => 18,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 16,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2020-02-10',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            88 => 
            array (
                'id' => 89,
                'user_id' => 90,
                'position_id' => 32,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 1,
                'blood_id' => 24,
                'start' => '1991-10-01',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            89 => 
            array (
                'id' => 90,
                'user_id' => 91,
                'position_id' => 33,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 21,
                'blood_id' => 30,
                'start' => '2019-05-06',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            90 => 
            array (
                'id' => 91,
                'user_id' => 92,
                'position_id' => 1,
                'department_id' => 3,
                'status_id' => 7,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 22,
                'blood_id' => 28,
                'start' => '2021-02-22',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            91 => 
            array (
                'id' => 92,
                'user_id' => 93,
                'position_id' => 10,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2019-01-03',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            92 => 
            array (
                'id' => 93,
                'user_id' => 94,
                'position_id' => 6,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 15,
                'level_id' => 20,
                'blood_id' => 27,
                'start' => '2014-07-07',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            93 => 
            array (
                'id' => 94,
                'user_id' => 95,
                'position_id' => 7,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 1,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2022-12-22',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            94 => 
            array (
                'id' => 95,
                'user_id' => 96,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 27,
                'start' => '2021-05-31',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            95 => 
            array (
                'id' => 96,
                'user_id' => 97,
                'position_id' => 1,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '1905-06-20',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            96 => 
            array (
                'id' => 97,
                'user_id' => 98,
                'position_id' => 4,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 31,
                'start' => '2019-11-21',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            97 => 
            array (
                'id' => 98,
                'user_id' => 99,
                'position_id' => 6,
                'department_id' => 4,
                'status_id' => 5,
                'office_id' => 11,
                'religion_id' => 15,
                'level_id' => 1,
                'blood_id' => 30,
                'start' => '2016-03-14',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            98 => 
            array (
                'id' => 99,
                'user_id' => 100,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 28,
                'start' => '2020-03-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:54',
                'updated_at' => '2022-12-20 21:06:54',
            ),
            99 => 
            array (
                'id' => 100,
                'user_id' => 101,
                'position_id' => 7,
                'department_id' => 4,
                'status_id' => 6,
                'office_id' => 10,
                'religion_id' => 1,
                'level_id' => 19,
                'blood_id' => 29,
                'start' => '2020-03-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:06:55',
            ),
            100 => 
            array (
                'id' => 101,
                'user_id' => 102,
                'position_id' => 1,
                'department_id' => 3,
                'status_id' => 5,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 1,
                'blood_id' => 28,
                'start' => '1991-12-16',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:06:55',
            ),
            101 => 
            array (
                'id' => 102,
                'user_id' => 103,
                'position_id' => 4,
                'department_id' => 3,
                'status_id' => 6,
                'office_id' => 12,
                'religion_id' => 13,
                'level_id' => 19,
                'blood_id' => 30,
                'start' => '2020-08-10',
                'end' => NULL,
                'created_at' => '2022-12-20 21:06:55',
                'updated_at' => '2022-12-20 21:06:55',
            ),
        ));
        
        
    }
}